### ISSUE TITLE
Login시 오류..

### ISSUE THREAD

**Issue by wildcong** [ryanking13/SRT#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Python\Python37-32\lib\site-packages\SRT\srt.py", line 66, in __init__
    self.login(srt_id, srt_pw)
  File "Python\Python37-32\lib\site-packages\SRT\srt.py", line 107, in login
    parser = SRTResponseData(r.text)
  File "Python\Python37-32\lib\site-packages\SRT\response_data.py", line 24, in __init__
    self._xml = ET.fromstring(response)
  File "Python\Python37-32\lib\xml\etree\ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49

**Comment by wildcong** [comment]
너무 늦게 확인했네요.. API 변경 감사합니다..
